[package]
name = "kibana-object-manager"
version = "0.1.0"
edition = "2024"
default-run = "kibob"
rust-version = "1.86"

[[bin]]
name = "kibob"
path = "src/main.rs"

[dependencies]
base64 = "^0.22"
clap = { version = "^4.5", features = ["derive"] }
dotenvy = "^0.15"
env_logger = "^0.11"
eyre = "^0.6"
jsrmx = "0.2.0"
log = "^0.4"
owo-colors = "4.2.0"
reqwest = { version = "^0.12", features = ["blocking", "json", "multipart"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
